version: '2' # specify docker-compose version

# Define the services/containers to be run
services:
  nginx:
    restart: always
    build: ./nginx
    links:
      - express:express
    ports:
      - "80:80"    
    volumes:
      - /etc/nginx/psw:/etc/nginx/psw
    environment:
      - DOMAIN_NAME=napi-shift-management-setup
  database: # name of the second service
    #build: ./mongo # specify the directory of the Dockerfile
    image: mongo:3.4
    command: mongod --port 27018
    ports:
      - "27018:27018" # specify port forewarding
    volumes:
      - mongo-datavolume:/data/mongodb/db #path store data
    # networks:
    #   mongo_net:
    #     ipv4_address: 172.19.0.2
  express: #name of the first service
    build: . # specify the directory of the Dockerfile
    ports:
      - "3000" #specify ports forewarding
    # networks:
    #   mongo_net:
    links:
      - database
    depends_on:
      - database
    environment: #specify enviroment variables for the app
      - MONGODBCON=mongodb://database:27018/shift-management-setup    
      - PORT=3000
      - NODE_ENV=dev
      - API_VERSION=v1
      - API_RESOURCE_ROOT=/api/v1
      - API_SERVER_TEST=http://localhost:4200
volumes:
  mongo-datavolume:
#see https://stackoverflow.com/questions/38860308/mongod-bind-ip-using-docker-compose-version-2
# networks:
#   mongo_net:
#     driver: bridge
#     ipam:
#       config:
#       - subnet: 172.19.0.0/24
#         gateway: 172.19.0.1